services:
  node:
    build: .
    command: [ "profiles", "create", "--name", "container_{{.Task.Slot}}", "--pass", "password" ]
    entrypoint: [ "python", "main.py" ]
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - testnet

  node_join:
    build: .
    command: [ "join" ]
    entrypoint: [ "python", "main.py" ]
    depends_on:
      - node
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - testnet

networks:
  testnet:
    driver: overlay
    attachable: true
